version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

    restart: always

volumes:
  mongodb_data_container:
